### ISSUE TITLE
Vue-cli-service not installed

### ISSUE THREAD

**Issue by choujar** [productscience/constellate#6]
Hi @mrchrisadams,

Although I can install this manually, I'm surprised that the 

`npm install`

didn't install vue-cli. I would've imagined it should? 

Thoughts?

Sahil

**Comment by choujar** [comment]
Thanks!

**Comment by choujar** [comment]
Just a note @mrchrisadams.

I'm running `npm install` on a healthy DO server with 1GB of RAM and it keeps getting killed - often at vuex installation but also sometimes at other points.

Didn't have this issue in the previous version.

Thoughts?

**Comment by mrchrisadams** [comment]
No, I'm not sure, why that would be.

This diff shows the extent of the changes - to the package.json file, 

https://github.com/productscience/constellate/pull/7/files

While the lockfile is clearly different, it seems strange that just adding vue would bork it like that, and I'm not able to read the package.json.lock right now to see what specifically is causing it.

It _might_ have happened if I had deleted the node_modules directory, the package.json.lock and _then_ tried a fresh reinstall - that _might_ have created a different lockfile, if there was no node_modules already installed. I don't understand npm's internals well enough to say so, sorry.

The best I can think of to remedy this is: 

1) Revert to the previous code, and previous lockfile

2) npm install as before

3) Add vue

```
npm install @vue/cli --save
```

4) See if the generated lockfile is dramatically different from the one in that diff, and has the same memory issues.

Hope that helps

**Comment by choujar** [comment]
Ok, so for now, I've gotten around it is actually by removing `vuex` and `firebase` from the dependencies... then running:
`npm install`

and then adding the removed packages after:

`npm install firebase --save`
`npm install vuex --save`

That worked!

**Comment by choujar** [comment]
If I do another fresh install, I'll try your suggested method above.
