### ISSUE TITLE
Airtable Spec

### ISSUE THREAD

**Issue by choujar** [productscience/constellate#8]
I think I already know the answer to this, but there's no spec for what the Airtable fields should be like, is there?

My best guess is:
1) a table called "Peeps" and "email" as the only field?
2) a table called "Tags" with "tag" as the only field?

Thanks in advance!

**Comment by mrchrisadams** [comment]
hi @choujar Sorry about the slow reply - I thought I was already reaching this repo, so would receive notifications on issues. 

Here's a link to a sample database I was working from before. I haven't tried keeping it in sync with fields in the Vue App, but it should give an idea of what the data looks like.

https://airtable.com/invite/l?inviteId=invzDawEmLv8dU405&inviteToken=2a609104a00e31b2ca25b3c506674f35a18898bccffebbd0c693ac0649d7d8e2

**Comment by choujar** [comment]
@mrchrisadams - I was travelling, so just saw this.

Thanks a bunch!
